# PBS flags
queue: express
project: v45
walltime: 0:30:00
ncpus: 120
mem: 128GB
jobname: mom-sis-01
qsub_flags: -W group_list=v45

#
#collate_walltime: 10:00:00
#collate_mem: 16GB
collate_walltime: 4:00:00
collate_mem: 30GB
collate_ncpus: 1
collate_queue: copyq
collate_flags: -n4 -z -m -x
collate: true

# Model config
model: mom
shortpath: /short/v45
exe: fms_MOM_SIS.intel14.fpe0.O2.ompi1.10.2
input: 
       - mom10/mosaic
       - mom10/common
       - /short/v45/fbd581/mom/input/CNYF_v2 

# Misc
stacksize: unlimited
