# PBS flags
queue: express
project: v45
walltime: 1:00:00
ncpus: 120
mem: 240GB
jobname: mom-sis-01
qsub_flags: -W group_list=v45
runspersub: 5

#
#collate_walltime: 10:00:00
#collate_mem: 16GB
collate_walltime: 4:00:00
collate_mem: 30GB
collate_ncpus: 1
collate_queue: express
collate_flags: -n4 -z -m -r
collate: true

archive: true

exe_prefix: /short/public/aph502/env-wrapper.sh  

# Model config
model: mom
shortpath: /short/v45
exe: fms_MOM_SIS.intel14.fpe0.O2.ompi1.10.2
input: 
       - mom10/mosaic
       - mom10/common
       - /g/data/v45/mom/cnyf2
       - /g/data1/ua8/MOM/runoff/JRA55-do/v1-1/mom10/RYF9091
       - mom10/mask_120/

# Misc
stacksize: unlimited

runlog: true

# runlog:
#    username: aidanheerdegen

# postscript: sync_to_gdata.sh
