# PBS flags
queue: express
project: x77
walltime: 1:00:00
ncpus: 120
mem: 128GB
jobname: mom-sis-01
qsub_flags: -W group_list=v45

#
#collate_walltime: 10:00:00
#collate_mem: 16GB
collate_walltime: 4:00:00
collate_mem: 30GB
collate_ncpus: 1
collate_queue: copyq
collate_flags: -n4 -z -m -r
collate: true

# Model config
model: mom
shortpath: /short/v45
exe: fms_MOM_SIS.intel14.fpe0.O2.ompi1.10.2
input: 
       - mom10/mosaic
       - mom10/common
       - /short/v45/fbd581/mom/input/CNYF_v2 
       - /g/data1/ua8/MOM/runoff/JRA55-do/v1-1/mom10/RYF9091

# Misc
stacksize: unlimited

runlog:
   username: aidanheerdegen

# postscript: sync_to_gdata.sh
